MODEL:
  MODEL_NAME: "yanolja/EEVE-Korean-10.8B-v1.0"
  MODEL_SHORT_NAME: "eeve-10.8B"
  EMBEDDING_MODEL_NAME: "jhgan/ko-sbert-nli"
  SEARCH_TYPE: "similarity"
  MAX_NEW_TOKENS: 150

DATA:
  CHUNK_SIZE: 300
  CHUNK_OVERLAP: 0
  MAX_DOCS: 3
  RETRIEVER_TYPE: "FAISS"

SEED: 100
QA_PATH: './data/qa_dataset/qa_pairs_cleaned.json'
QA_TEST_PATH: './data/qa_dataset/qa_test_data_500.json'
DATA_PATH: './data/vectorstore/all_merged_law_text_list.json'
DATASTORE_PATH: './data/vectorstore/datastore.json'
VECTORSTORE_PATH: './data/vectorstore/vectorstore.pkl'
PROMPT_PATH: './prompt/RAG_Prompt.txt'
RESULT_PATH: './results/'